# Generated by Django 4.0.6 on 2022-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exsite',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='exsite',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='exsite',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='exsite',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exsite',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exsite',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exsite',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exsite',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
