# Generated by Django 4.0.6 on 2022-10-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_exsite_facebook_remove_exsite_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exsite',
            name='og_image',
            field=models.ImageField(upload_to='bg'),
        ),
    ]
