# Generated by Django 4.0.6 on 2023-09-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyraw',
            name='type',
            field=models.CharField(blank=True, help_text="The type of your literature (e.g., 'Story, Novel').", max_length=200, null=True),
        ),
    ]
