# Generated by Django 4.0.6 on 2023-09-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0006_storyraw_created_storyraw_updated_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='story',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='story',
        #     name='story_outline',
        #     field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='literature.storyoutline'),
        # ),
    ]
