# Generated by Django 4.0.6 on 2023-09-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0007_remove_story_id_alter_story_story_outline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
