# Generated by Django 4.0.6 on 2023-09-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0009_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sigment_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyoutline',
            name='segment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
