# Generated by Django 4.0.6 on 2023-09-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0012_alter_storyraw_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyoutline',
            name='story_raw',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='StoryOutline',
        ),
        migrations.DeleteModel(
            name='StoryRaw',
        ),
    ]
