# Generated by Django 4.0.6 on 2023-09-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('literature', '0013_remove_storyoutline_story_raw_delete_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('idea_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoryOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_outline', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='literature.storyoutline')),
                ('sigment_story', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryRaw',
            fields=[
                ('idea', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='literature.ideautilization')),
                ('title', models.CharField(blank=True, help_text='It an keep blank to add from response of chatGPT', max_length=250, null=True)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Poetry', 'Poetry'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Historical Fiction', 'Historical Fiction'), ('Science Fiction', 'Science Fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Memoir', 'Memoir'), ('Satire', 'Satire'), ('Fable', 'Fable'), ('Children Literature', 'Children Literature')], help_text='Select the genre of your story.', max_length=50)),
                ('type', models.CharField(help_text="The type of your literature (e.g., 'Essay, Drama, Poem, Story, Novel, Short Story, Epic').", max_length=200)),
                ('character', models.CharField(blank=True, help_text="The main character in your story (e.g., 'Detective John Smith').", max_length=200, null=True)),
                ('setting', models.CharField(blank=True, help_text="The primary setting of your story. An specific time, session or location (e.g., 'future, Victorian London').", max_length=200, null=True)),
                ('conflict', models.TextField(blank=True, help_text='Describe the central conflict or problem in your story.', null=True)),
                ('tone', models.CharField(blank=True, help_text="The tone of your story (e.g., 'Classical, Baroque, Victorian, Realistic, Modernist, Surrealistic, Naturalistic, Absurdist, Epic, Tragic, Mysterious', 'Romantic').", max_length=50, null=True)),
                ('style', models.CharField(blank=True, help_text="The narrative style (e.g., 'First-person', 'Third-person, Third-Person Limited, Third-Person Omniscient, Second-Person, Epistolary, Stream of Consciousness, Multi-Person, Unreliable Narrator, Framed Narrative').", max_length=50, null=True)),
                ('topic', models.CharField(blank=True, help_text="Specify the topic or subject of your non-fiction story (e.g., 'History of Space Exploration').", max_length=200, null=True)),
                ('purpose', models.CharField(blank=True, help_text="Describe the purpose of your non-fiction story (e.g., 'Inform readers about scientific discoveries').", max_length=200, null=True)),
                ('audience', models.CharField(blank=True, help_text="Identify the target audience for your non-fiction story (e.g., 'General readers', 'Experts').", max_length=200, null=True)),
                ('key_points', models.TextField(blank=True, help_text='List key points, facts, or information you want in your non-fiction story.', null=True)),
                ('theme', models.CharField(blank=True, help_text="The central theme of your story (e.g., 'Love', 'Adventure, Conflict, Identity, Coming of Age, Power and Corruption, Justice and Injustice, Isolation and Alienation, Nature vs. Nurture, Freedom and Oppression, Death and Mortality, Friendship, Ambition and Desire, Society and Social Change, Betrayal, Memory and Nostalgia, Hope and Despair, Technology and Progress, Family, Survival, Fate and Free Will, Redemption').", max_length=50, null=True)),
                ('mood', models.CharField(blank=True, help_text="The mood or emotional atmosphere of your story (e.g., 'Joyful', 'Melancholic, Eerie, Tense, Gloomy, Whimsical, Nostalgic, Serene, Horrific, Humorous, Surreal, Romantic, Mysterious, Empowering, Regretful, Hopeful').", max_length=50, null=True)),
                ('rhyme_meter', models.CharField(blank=True, help_text="Specify the rhyme scheme or meter for your poem (e.g., 'ABAB', 'Haiku, Sonnet, Limerick, Villanelle, Pantoum, Sestina, Tanka, Ghazal, Ode, Ballad, Triolet').", max_length=50, null=True)),
                ('imagery_symbolism', models.TextField(blank=True, help_text='Describe any specific imagery or symbolism you want in your poem.', null=True)),
                ('characters', models.TextField(blank=True, help_text="Describe the main characters in your drama (e.g., 'Character A: Ambitious detective').", null=True)),
                ('scenes', models.TextField(blank=True, help_text='Outline key scenes or settings in your drama.', null=True)),
                ('dialogue', models.TextField(blank=True, help_text='Provide dialogue prompts for important interactions in your drama.', null=True)),
                ('world_building', models.TextField(blank=True, help_text='Describe the unique world or setting in your fantasy story.', null=True)),
                ('species', models.TextField(blank=True, help_text='Introduce unique species or beings in your fantasy story.', null=True)),
                ('quest', models.TextField(blank=True, help_text='Outline the main quest or adventure in your fantasy story.', null=True)),
                ('crime', models.TextField(blank=True, help_text='Describe the central crime or mystery that needs solving in your mystery story.', null=True)),
                ('detective', models.CharField(blank=True, help_text='Introduce the detective or protagonist tasked with solving the mystery.', max_length=200, null=True)),
                ('clues_red_herrings', models.TextField(blank=True, help_text='Suggest clues and potential red herrings to make the mystery engaging.', null=True)),
                ('time_period', models.CharField(blank=True, help_text='Specify the historical time period in your historical fiction story.', max_length=200, null=True)),
                ('historical_figures', models.TextField(blank=True, help_text='Mention any real historical figures or events you want to include in your story.', null=True)),
                ('character_arcs', models.TextField(blank=True, help_text='Describe character arcs or development for characters in your historical fiction story.', null=True)),
                ('meet_cute', models.TextField(blank=True, help_text="Describe the initial encounter or 'meet-cute' between romantic leads in your romance story.", null=True)),
                ('obstacles_to_love', models.TextField(blank=True, help_text='Highlight obstacles, conflicts, or misunderstandings that challenge the romance in your story.', null=True)),
                ('resolution', models.TextField(blank=True, help_text='Indicate how the romantic relationship should evolve and conclude.', null=True)),
                ('atmosphere', models.TextField(blank=True, help_text='Describe the eerie or unsettling atmosphere in your horror story.', null=True)),
                ('threat_entity', models.TextField(blank=True, help_text='Specify the nature of the threat, monster, or entity causing fear in your horror story.', null=True)),
                ('suspense_dread', models.TextField(blank=True, help_text='Emphasize building suspense and a sense of dread in your horror story.', null=True)),
                ('age_group', models.CharField(blank=True, help_text="Specify the target age group for your children's literature (e.g., 'Ages 5-8').", max_length=50, null=True)),
                ('moral_lesson', models.TextField(blank=True, help_text="Include any moral lessons or messages you want to convey in your children's literature story.", null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='storyoutline',
            name='story_raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyoutline', to='literature.storyraw'),
        ),
    ]
