# Generated by Django 4.0.6 on 2023-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideautilization',
            name='idea_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
