# Generated by Django 4.0.6 on 2023-09-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0015_alter_ideautilization_idea_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideautilization',
            name='idea_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
