# Generated by Django 4.0.6 on 2023-09-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0017_alter_storyraw_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyraw',
            name='theme',
            field=models.TextField(blank=True, help_text="The central theme of your story (e.g., 'Love', 'Adventure, Conflict, Identity, Coming of Age, Power and Corruption, Justice and Injustice, Isolation and Alienation, Nature vs. Nurture, Freedom and Oppression, Death and Mortality, Friendship, Ambition and Desire, Society and Social Change, Betrayal, Memory and Nostalgia, Hope and Despair, Technology and Progress, Family, Survival, Fate and Free Will, Redemption').", max_length=50, null=True),
        ),
    ]
