# Generated by Django 4.0.6 on 2023-09-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0019_alter_storyraw_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyraw',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Poetry', 'Poetry'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Historical Fiction', 'Historical Fiction'), ('Science Fiction', 'Science Fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Memoir', 'Memoir'), ('Satire', 'Satire'), ('Fable', 'Fable'), ('Social Realism', 'Social Realism'), ('Children Literature', 'Children Literature')], help_text='Select the genre of your story.', max_length=250),
        ),
        migrations.AlterField(
            model_name='storyraw',
            name='style',
            field=models.TextField(blank=True, help_text="The narrative style (e.g., 'First-person', 'Third-person, Third-Person Limited, Third-Person Omniscient, Second-Person, Epistolary, Stream of Consciousness, Multi-Person, Unreliable Narrator, Framed Narrative').", null=True),
        ),
        migrations.AlterField(
            model_name='storyraw',
            name='theme',
            field=models.TextField(blank=True, help_text="The central theme of your story (e.g., 'Love', 'Adventure, Conflict, Identity, Coming of Age, Power and Corruption, Justice and Injustice, Isolation and Alienation, Nature vs. Nurture, Freedom and Oppression, Death and Mortality, Friendship, Ambition and Desire, Society and Social Change, Betrayal, Memory and Nostalgia, Hope and Despair, Technology and Progress, Family, Survival, Fate and Free Will, Redemption').", null=True),
        ),
    ]
