# Generated by Django 4.0.6 on 2023-09-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0020_alter_storyraw_genre_alter_storyraw_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyoutline',
            name='segment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
