# Generated by Django 4.0.6 on 2023-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0021_alter_storyoutline_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyoutline',
            name='segment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
