# Generated by Django 4.0.6 on 2023-09-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0022_alter_storyoutline_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideautilization',
            name='idea',
            field=models.TextField(help_text='The place is to describe ideas to get best parameters to write literature. Primarily system will suggest title, genre, type, main charecter, settings, conflict, tone, style, topic,purpose, audience, keypoints, theme, mood, species quest.', max_length=500, verbose_name='Describe your idea in maximum 500 characters'),
        ),
        migrations.AlterField(
            model_name='storyoutline',
            name='segment',
            field=models.TextField(blank=True, help_text='Story will be created based on the outline provided in this segment. But you have the flexibility to edit the outline.', null=True),
        ),
    ]
