# Generated by Django 4.0.6 on 2023-09-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0026_alter_ideautilization_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideautilization',
            name='idea',
            field=models.TextField(help_text='The place is to describe ideas to get best parameters to write literature. Primarily system will suggest title, genre, type, main charecter, settings, conflict, tone, style, topic,purpose, audience, keypoints, theme, mood, species quest.', verbose_name='Describe your idea in maximum 500 characters'),
        ),
    ]
