# Generated by Django 4.0.6 on 2023-09-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0027_alter_ideautilization_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyraw',
            name='genre',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Poetry', 'Poetry'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Historical Fiction', 'Historical Fiction'), ('Science Fiction', 'Science Fiction'), ('Realistic  Fiction', 'Realistic  Fiction'), ('Dystopian  Fiction', 'Dystopian  Fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Memoir', 'Memoir'), ('Satire', 'Satire'), ('Fable', 'Fable'), ('Tragedy', 'Tragedy'), ('Suspense', 'Suspense'), ('Thriller', 'Thriller'), ('Political Thriller', 'Political Thriller'), ('Drama', 'Drama'), ('Social Realism', 'Social Realism'), ('Children Literature', 'Children Literature')], help_text='Select the genre of your story.', max_length=250, null=True),
        ),
    ]
