# Generated by Django 4.0.6 on 2023-09-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0029_story_id_alter_story_story_outline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
