# Generated by Django 4.0.6 on 2023-09-28 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0030_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigment_story', models.TextField(blank=True, null=True)),
                ('story_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.storyoutline')),
            ],
        ),
    ]
