# Generated by Django 4.0.6 on 2023-09-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0031_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_outline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='literature.storyoutline'),
        ),
    ]
