# Generated by Django 4.0.6 on 2022-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sense', '0002_alter_sensepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensepost',
            name='view',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
