# Generated by Django 4.0.6 on 2022-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='photo',
            field=models.ImageField(default='', upload_to='me_photo'),
            preserve_default=False,
        ),
    ]
