# Generated by Django 4.0.6 on 2022-07-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_alter_me_me_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upwork', models.URLField(blank=True)),
                ('fivrr', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('me', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milinks', to='bio.me')),
            ],
        ),
    ]
