# Generated by Django 4.0.6 on 2022-07-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_mylinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylinks',
            old_name='facebook',
            new_name='links',
        ),
        migrations.RemoveField(
            model_name='mylinks',
            name='fivrr',
        ),
        migrations.RemoveField(
            model_name='mylinks',
            name='github',
        ),
        migrations.RemoveField(
            model_name='mylinks',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='mylinks',
            name='upwork',
        ),
        migrations.AddField(
            model_name='mylinks',
            name='incon',
            field=models.ImageField(default='', upload_to='link_icons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mylinks',
            name='text_to_show',
            field=models.CharField(default='', max_length=252),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mylinks',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylinks', to='bio.me'),
        ),
    ]
