# Generated by Django 4.0.6 on 2022-07-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_rename_facebook_mylinks_links_remove_mylinks_fivrr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylinks',
            old_name='incon',
            new_name='icon',
        ),
    ]
