# Generated by Django 4.0.6 on 2022-07-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0008_alter_mylinks_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_of_skill', models.CharField(max_length=252)),
                ('skill_in', models.TextField()),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myskills', to='bio.me')),
            ],
        ),
    ]
