# Generated by Django 4.0.6 on 2022-07-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0009_myskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskills',
            name='ex_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
