# Generated by Django 4.0.6 on 2022-07-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0010_myskills_ex_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myskills',
            name='ex_link',
        ),
    ]
