# Generated by Django 4.0.6 on 2022-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0011_remove_myskills_ex_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='myskills',
            name='skill_in',
        ),
        migrations.AddField(
            model_name='myskills',
            name='skills_in',
            field=models.ManyToManyField(related_name='skillsin', to='bio.skillsin'),
        ),
    ]
