# Generated by Django 4.0.6 on 2022-07-12 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0012_skillsin_remove_myskills_skill_in_myskills_skills_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('description', models.TextField()),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myservice', to='bio.me')),
            ],
        ),
    ]
