# Generated by Django 4.0.6 on 2022-07-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0013_servicecategory_myservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('color_hex', models.CharField(max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('delivery_time', models.CharField(max_length=5)),
                ('revision', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='myservice',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='myservice',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='bio.servicecategory'),
        ),
        migrations.AddField(
            model_name='myservice',
            name='mp_links',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myservice',
            name='picture',
            field=models.ImageField(default='', upload_to='service_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myservice',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myservice',
            name='service_option',
            field=models.ManyToManyField(related_name='options', to='bio.serviceoption'),
        ),
    ]
