# Generated by Django 4.0.6 on 2022-07-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0015_alter_myservice_slug_alter_servicecategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myservice',
            name='service_option',
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='myservice', to='bio.myservice'),
            preserve_default=False,
        ),
    ]
