# Generated by Django 4.0.6 on 2022-07-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0016_remove_myservice_service_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
