# Generated by Django 4.0.6 on 2022-07-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0019_serviceimage_description_serviceimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myservice',
            name='skills_involved',
            field=models.ManyToManyField(related_name='skillsinservice', to='bio.skillsin'),
        ),
    ]
