# Generated by Django 4.0.6 on 2022-07-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0020_myservice_skills_involved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOfOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('value', models.CharField(max_length=252)),
            ],
        ),
    ]
