# Generated by Django 4.0.6 on 2022-07-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0021_extraofoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoption',
            name='select_aditional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='bio.extraofoptions'),
        ),
    ]
