# Generated by Django 4.0.6 on 2022-07-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0024_serviceoption_select_aditional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoption',
            name='select_aditional',
        ),
        migrations.AddField(
            model_name='extraofoptions',
            name='option',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='bio.serviceoption'),
            preserve_default=False,
        ),
    ]
