# Generated by Django 4.0.6 on 2022-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0025_remove_serviceoption_select_aditional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myservice',
            name='dark_class',
            field=models.CharField(default='bg-dark', max_length=15),
        ),
        migrations.AddField(
            model_name='myservice',
            name='light_class',
            field=models.CharField(default='bg-light', max_length=15),
        ),
    ]
