# Generated by Django 4.0.6 on 2022-07-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0029_myworks_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='title',
            field=models.CharField(max_length=152),
        ),
    ]
