# Generated by Django 4.0.6 on 2022-07-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0030_alter_myworks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
