# Generated by Django 4.0.6 on 2022-07-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0033_alter_myworks_short_des_alter_myworks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='skills_involved',
            field=models.ManyToManyField(related_name='skillsinworks', to='bio.skillsin'),
        ),
    ]
