# Generated by Django 4.0.6 on 2022-07-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0034_alter_myworks_skills_involved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workimage',
            name='work',
        ),
        migrations.DeleteModel(
            name='MyWorks',
        ),
        migrations.DeleteModel(
            name='WorkImage',
        ),
    ]
