# Generated by Django 4.0.6 on 2022-07-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0036_myworks_workimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myworks',
            old_name='Description',
            new_name='description',
        ),
    ]
