# Generated by Django 4.0.6 on 2022-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0037_rename_description_myworks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsin',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
