# Generated by Django 4.0.6 on 2022-07-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0038_alter_skillsin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsin',
            name='link',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
