# Generated by Django 4.0.6 on 2022-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0040_serviceimage_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
            ],
        ),
    ]
