# Generated by Django 4.0.6 on 2022-07-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0041_extralabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraofoptions',
            name='name',
        ),
        migrations.AddField(
            model_name='extraofoptions',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exlabel', to='bio.extralabel'),
        ),
    ]
