# Generated by Django 4.0.6 on 2022-07-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0042_remove_extraofoptions_name_extraofoptions_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='extralabel',
            name='l_for',
            field=models.CharField(choices=[('', 'Select You Looking For'), ('web', 'Web'), ('fashion', 'Fashion')], default='web', max_length=10),
        ),
    ]
