# Generated by Django 4.0.6 on 2022-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0043_extralabel_l_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylinks',
            name='to_cv',
            field=models.BooleanField(default=True),
        ),
    ]
