# Generated by Django 4.0.6 on 2022-07-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0045_skillsin_skil_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('type', models.CharField(max_length=252)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylang', to='bio.me')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('type', models.CharField(max_length=252)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myinterest', to='bio.me')),
            ],
        ),
    ]
