# Generated by Django 4.0.6 on 2022-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0048_remove_interest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('school', models.CharField(blank=True, max_length=252, null=True)),
                ('period', models.CharField(blank=True, max_length=252, null=True)),
            ],
        ),
    ]
