# Generated by Django 4.0.6 on 2022-07-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0049_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myeducation', to='bio.me'),
            preserve_default=False,
        ),
    ]
