# Generated by Django 4.0.6 on 2022-07-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0050_education_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252)),
                ('summary', models.TextField()),
                ('achivements', models.TextField()),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexperience', to='bio.me')),
                ('related_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedwork', to='bio.myworks')),
            ],
        ),
    ]
