# Generated by Django 4.0.6 on 2022-07-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0051_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='period',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
