# Generated by Django 4.0.6 on 2022-08-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0052_workexperience_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='serial',
            field=models.BigIntegerField(default=0),
        ),
    ]
