# Generated by Django 4.0.6 on 2022-08-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0053_workexperience_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
