# Generated by Django 4.0.6 on 2022-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0054_workexperience_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsin',
            name='show_in_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skillsin',
            name='show_in_front',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skillsin',
            name='show_in_service_details',
            field=models.BooleanField(default=True),
        ),
    ]
