# Generated by Django 4.0.6 on 2022-09-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0055_skillsin_show_in_cv_skillsin_show_in_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myservice',
            name='skills_involved',
        ),
        migrations.AddField(
            model_name='myservice',
            name='skills_involved',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skillsinservice', to='bio.myskills'),
            preserve_default=False,
        ),
    ]
