# Generated by Django 4.0.6 on 2022-09-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0056_remove_myservice_skills_involved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myservice',
            name='skills_involved',
        ),
        migrations.AddField(
            model_name='myservice',
            name='skills_involved',
            field=models.ManyToManyField(related_name='skillsinservice', to='bio.myskills'),
        ),
    ]
