# Generated by Django 4.0.6 on 2022-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0057_remove_myservice_skills_involved_and_more'),
    ]

    operations = [
        
    ]
