# Generated by Django 4.0.6 on 2022-09-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0059_remove_myworks_skills_involved'),
    ]

    operations = [
        
    ]
