# Generated by Django 4.0.6 on 2022-09-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0064_alter_myworks_skills_involved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myworks',
            name='skills_involved',
        ),
    ]
