# Generated by Django 4.0.6 on 2022-09-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0065_remove_myworks_skills_involved'),
    ]

    operations = [
        migrations.AddField(
            model_name='myworks',
            name='skills_involved',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skillsinworks', to='bio.myskills'),
            preserve_default=False,
        ),
    ]
