# Generated by Django 4.0.6 on 2022-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0066_myworks_skills_involved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myworks',
            name='skills_involved',
        ),
        migrations.AddField(
            model_name='myworks',
            name='skills_involved',
            field=models.ManyToManyField(related_name='skillsinworks', to='bio.myskills'),
        ),
    ]
