# Generated by Django 4.0.6 on 2022-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0067_remove_myworks_skills_involved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsin',
            name='show_in_work_details',
            field=models.BooleanField(default=True),
        ),
    ]
