# Generated by Django 4.0.6 on 2022-09-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0068_skillsin_show_in_work_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsin',
            name='show_in_cv_tech',
            field=models.BooleanField(default=True),
        ),
    ]
