# Generated by Django 4.0.6 on 2022-10-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0069_skillsin_show_in_cv_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extralabel',
            name='l_for',
            field=models.CharField(choices=[('', 'Choose the area in which you need help...'), ('web', 'Web Development'), ('fashion', 'Fashion Technology')], default='web', max_length=10),
        ),
        migrations.AlterField(
            model_name='me',
            name='me_for',
            field=models.CharField(choices=[('', 'Choose the area in which you need help...'), ('web', 'Web Development'), ('fashion', 'Fashion Technology')], max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('digital_pic', models.ImageField(upload_to='certificate')),
                ('valid_link', models.URLField()),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='bio.me')),
            ],
        ),
    ]
