# Generated by Django 4.0.6 on 2022-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0071_alter_extralabel_l_for_alter_me_me_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myservice',
            name='dark_class',
        ),
        migrations.RemoveField(
            model_name='myservice',
            name='light_class',
        ),
        migrations.AddField(
            model_name='myservice',
            name='dark_body_class',
            field=models.CharField(default='bg-lightgrey', max_length=15),
        ),
        migrations.AddField(
            model_name='myservice',
            name='dark_head_class',
            field=models.CharField(default='bg-deepgrey', max_length=15),
        ),
        migrations.AddField(
            model_name='myservice',
            name='light_body_class',
            field=models.CharField(default='bg-brightbeige', max_length=15),
        ),
        migrations.AddField(
            model_name='myservice',
            name='light_head_class',
            field=models.CharField(default='bg-darkbeige', max_length=15),
        ),
    ]
