# Generated by Django 4.0.6 on 2022-10-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0072_remove_myservice_dark_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myservice',
            name='dark_link_class',
            field=models.CharField(default='link-lightgrey', max_length=15),
        ),
        migrations.AddField(
            model_name='myservice',
            name='light_link_class',
            field=models.CharField(default='link-brightbeige', max_length=25),
        ),
    ]
