# Generated by Django 4.0.6 on 2023-03-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0075_workexperience_tech_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='tech_used',
            field=models.ManyToManyField(related_name='skillsinex', to='bio.skillsin'),
        ),
    ]
