# Generated by Django 4.0.6 on 2023-03-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0076_alter_workexperience_tech_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='tech_used',
        ),
    ]
